
package com.uba.waei.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Service", targetNamespace = "http://ws.waei.uba.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Service {


    /**
     * 
     * @param request
     * @return
     *     returns com.uba.waei.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createNewCorporateEntrustUser", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.CreateNewCorporateEntrustUser")
    @ResponseWrapper(localName = "createNewCorporateEntrustUserResponse", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.CreateNewCorporateEntrustUserResponse")
    @Action(input = "http://ws.waei.uba.com/Service/createNewCorporateEntrustUserRequest", output = "http://ws.waei.uba.com/Service/createNewCorporateEntrustUserResponse")
    public Response createNewCorporateEntrustUser(
            @WebParam(name = "request", targetNamespace = "")
                    CorporateUser request);

    /**
     * 
     * @param request
     * @return
     *     returns com.uba.waei.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createNewOrUpdateUserQA", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.CreateNewOrUpdateUserQA")
    @ResponseWrapper(localName = "createNewOrUpdateUserQAResponse", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.CreateNewOrUpdateUserQAResponse")
    @Action(input = "http://ws.waei.uba.com/Service/createNewOrUpdateUserQARequest", output = "http://ws.waei.uba.com/Service/createNewOrUpdateUserQAResponse")
    public Response createNewOrUpdateUserQA(
            @WebParam(name = "request", targetNamespace = "")
                    QaRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.uba.waei.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createNewEntrustUser", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.CreateNewEntrustUser")
    @ResponseWrapper(localName = "createNewEntrustUserResponse", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.CreateNewEntrustUserResponse")
    @Action(input = "http://ws.waei.uba.com/Service/createNewEntrustUserRequest", output = "http://ws.waei.uba.com/Service/createNewEntrustUserResponse")
    public Response createNewEntrustUser(
            @WebParam(name = "request", targetNamespace = "")
                    RetailUser request);

    /**
     * 
     * @param request
     * @return
     *     returns com.uba.waei.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "synchronizeToken", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.SynchronizeToken")
    @ResponseWrapper(localName = "synchronizeTokenResponse", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.SynchronizeTokenResponse")
    @Action(input = "http://ws.waei.uba.com/Service/synchronizeTokenRequest", output = "http://ws.waei.uba.com/Service/synchronizeTokenResponse")
    public Response synchronizeToken(
            @WebParam(name = "request", targetNamespace = "")
                    ResetToken request);

    /**
     * 
     * @param request
     * @return
     *     returns com.uba.waei.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOneSecurityQuestion", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.GetOneSecurityQuestion")
    @ResponseWrapper(localName = "getOneSecurityQuestionResponse", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.GetOneSecurityQuestionResponse")
    @Action(input = "http://ws.waei.uba.com/Service/getOneSecurityQuestionRequest", output = "http://ws.waei.uba.com/Service/getOneSecurityQuestionResponse")
    public Response getOneSecurityQuestion(
            @WebParam(name = "request", targetNamespace = "")
                    GetOneSecurityQuestionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.uba.waei.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authenticateSecurityQuestion", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.AuthenticateSecurityQuestion")
    @ResponseWrapper(localName = "authenticateSecurityQuestionResponse", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.AuthenticateSecurityQuestionResponse")
    @Action(input = "http://ws.waei.uba.com/Service/authenticateSecurityQuestionRequest", output = "http://ws.waei.uba.com/Service/authenticateSecurityQuestionResponse")
    public Response authenticateSecurityQuestion(
            @WebParam(name = "request", targetNamespace = "")
                    AuthenticateSecurityQuestionRequest request);

    /**
     * 
     * @param biometricData
     * @param isSuccessful
     * @param response
     * @param errorResponseMessage
     * @param errorResponseCode
     * @param vendorId
     * @param comment
     * @param clearBiometricData
     * @param userGroup
     * @param enrollParameters
     * @param username
     */
    @WebMethod
    @RequestWrapper(localName = "addBiometricData", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.AddBiometricData")
    @ResponseWrapper(localName = "addBiometricDataResponse", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.AddBiometricDataResponse")
    @Action(input = "http://ws.waei.uba.com/Service/addBiometricDataRequest", output = "http://ws.waei.uba.com/Service/addBiometricDataResponse")
    public void addBiometricData(
            @WebParam(name = "username", targetNamespace = "", mode = WebParam.Mode.INOUT)
                    Holder<String> username,
            @WebParam(name = "userGroup", targetNamespace = "", mode = WebParam.Mode.INOUT)
                    Holder<String> userGroup,
            @WebParam(name = "vendorId", targetNamespace = "")
                    String vendorId,
            @WebParam(name = "biometricData", targetNamespace = "")
                    byte[] biometricData,
            @WebParam(name = "enrollParameters", targetNamespace = "")
                    List<NameValue> enrollParameters,
            @WebParam(name = "clearBiometricData", targetNamespace = "")
                    Boolean clearBiometricData,
            @WebParam(name = "comment", targetNamespace = "")
                    String comment,
            @WebParam(name = "isSuccessful", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> isSuccessful,
            @WebParam(name = "response", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> response,
            @WebParam(name = "errorResponseCode", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> errorResponseCode,
            @WebParam(name = "errorResponseMessage", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> errorResponseMessage);

    /**
     * 
     * @param request
     * @return
     *     returns com.uba.waei.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateOrCreateuserContactInfo", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.UpdateOrCreateuserContactInfo")
    @ResponseWrapper(localName = "updateOrCreateuserContactInfoResponse", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.UpdateOrCreateuserContactInfoResponse")
    @Action(input = "http://ws.waei.uba.com/Service/updateOrCreateuserContactInfoRequest", output = "http://ws.waei.uba.com/Service/updateOrCreateuserContactInfoResponse")
    public Response updateOrCreateuserContactInfo(
            @WebParam(name = "request", targetNamespace = "")
                    UserContactDetailList request);

    /**
     * 
     * @param request
     * @return
     *     returns com.uba.waei.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.DeleteUserResponse")
    @Action(input = "http://ws.waei.uba.com/Service/deleteUserRequest", output = "http://ws.waei.uba.com/Service/deleteUserResponse")
    public Response deleteUser(
            @WebParam(name = "request", targetNamespace = "")
                    DeleteUserRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.uba.waei.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authenticateToken", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.AuthenticateToken")
    @ResponseWrapper(localName = "authenticateTokenResponse", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.AuthenticateTokenResponse")
    @Action(input = "http://ws.waei.uba.com/Service/authenticateTokenRequest", output = "http://ws.waei.uba.com/Service/authenticateTokenResponse")
    public Response authenticateToken(
            @WebParam(name = "request", targetNamespace = "")
                    AuthenticateTokenRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.uba.waei.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "adaptiveAuthentication", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.AdaptiveAuthentication")
    @ResponseWrapper(localName = "adaptiveAuthenticationResponse", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.AdaptiveAuthenticationResponse")
    @Action(input = "http://ws.waei.uba.com/Service/adaptiveAuthenticationRequest", output = "http://ws.waei.uba.com/Service/adaptiveAuthenticationResponse")
    public Response adaptiveAuthentication(
            @WebParam(name = "request", targetNamespace = "")
                    AdaptiveAuthenticationRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.uba.waei.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createEntrustUser", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.CreateEntrustUser")
    @ResponseWrapper(localName = "createEntrustUserResponse", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.CreateEntrustUserResponse")
    @Action(input = "http://ws.waei.uba.com/Service/createEntrustUserRequest", output = "http://ws.waei.uba.com/Service/createEntrustUserResponse")
    public Response createEntrustUser(
            @WebParam(name = "request", targetNamespace = "")
                    RetailUser request);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.uba.waei.ws.UserSetResponse
     */
    @WebMethod
    @WebResult(name = "userSetCallParmsResponse", targetNamespace = "http://ws.waei.uba.com/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://ws.waei.uba.com/Service/userSetCallParmsRequest", output = "http://ws.waei.uba.com/Service/userSetCallParmsResponse")
    public UserSetResponse userSet(
            @WebParam(name = "userSetCallParms", targetNamespace = "http://ws.waei.uba.com/", partName = "parameters")
                    UserSet parameters);

    /**
     * 
     * @param biometricData
     * @param isSuccessful
     * @param response
     * @param errorResponseMessage
     * @param errorResponseCode
     * @param userGroup
     * @param username
     */
    @WebMethod
    @RequestWrapper(localName = "authBiometric", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.AuthBiometric")
    @ResponseWrapper(localName = "authBiometricResponse", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.AuthBiometricResponse")
    @Action(input = "http://ws.waei.uba.com/Service/authBiometricRequest", output = "http://ws.waei.uba.com/Service/authBiometricResponse")
    public void authBiometric(
            @WebParam(name = "username", targetNamespace = "", mode = WebParam.Mode.INOUT)
                    Holder<String> username,
            @WebParam(name = "userGroup", targetNamespace = "", mode = WebParam.Mode.INOUT)
                    Holder<String> userGroup,
            @WebParam(name = "biometricData", targetNamespace = "")
                    byte[] biometricData,
            @WebParam(name = "isSuccessful", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> isSuccessful,
            @WebParam(name = "response", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> response,
            @WebParam(name = "errorResponseCode", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> errorResponseCode,
            @WebParam(name = "errorResponseMessage", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> errorResponseMessage);

    /**
     * 
     * @param request
     * @return
     *     returns com.uba.waei.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authenticateAdaptiveSecurityQuestion", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.AuthenticateAdaptiveSecurityQuestion")
    @ResponseWrapper(localName = "authenticateAdaptiveSecurityQuestionResponse", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.AuthenticateAdaptiveSecurityQuestionResponse")
    @Action(input = "http://ws.waei.uba.com/Service/authenticateAdaptiveSecurityQuestionRequest", output = "http://ws.waei.uba.com/Service/authenticateAdaptiveSecurityQuestionResponse")
    public Response authenticateAdaptiveSecurityQuestion(
            @WebParam(name = "request", targetNamespace = "")
                    AuthenticateSecurityQuestionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.uba.waei.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authenticateOTP", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.AuthenticateOTP")
    @ResponseWrapper(localName = "authenticateOTPResponse", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.AuthenticateOTPResponse")
    @Action(input = "http://ws.waei.uba.com/Service/authenticateOTPRequest", output = "http://ws.waei.uba.com/Service/authenticateOTPResponse")
    public Response authenticateOTP(
            @WebParam(name = "request", targetNamespace = "")
                    AuthenticateTokenRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.uba.waei.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generateOTP", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.GenerateOTP")
    @ResponseWrapper(localName = "generateOTPResponse", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.GenerateOTPResponse")
    @Action(input = "http://ws.waei.uba.com/Service/generateOTPRequest", output = "http://ws.waei.uba.com/Service/generateOTPResponse")
    public Response generateOTP(
            @WebParam(name = "request", targetNamespace = "")
                    OtpRequest request);

    /**
     * 
     * @param parequest
     * @return
     *     returns com.uba.waei.ws.BinaryResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createAuthenticationSecreet", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.CreateAuthenticationSecreet")
    @ResponseWrapper(localName = "createAuthenticationSecreetResponse", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.CreateAuthenticationSecreetResponse")
    @Action(input = "http://ws.waei.uba.com/Service/createAuthenticationSecreetRequest", output = "http://ws.waei.uba.com/Service/createAuthenticationSecreetResponse")
    public BinaryResponse createAuthenticationSecreet(
            @WebParam(name = "parequest", targetNamespace = "")
                    PaRequest parequest);

    /**
     * 
     * @param parequest
     * @return
     *     returns com.uba.waei.ws.BinaryResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchAuthenticationSecreet", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.FetchAuthenticationSecreet")
    @ResponseWrapper(localName = "fetchAuthenticationSecreetResponse", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.FetchAuthenticationSecreetResponse")
    @Action(input = "http://ws.waei.uba.com/Service/fetchAuthenticationSecreetRequest", output = "http://ws.waei.uba.com/Service/fetchAuthenticationSecreetResponse")
    public BinaryResponse fetchAuthenticationSecreet(
            @WebParam(name = "parequest", targetNamespace = "")
                    PaRequest parequest);

    /**
     * 
     * @param requesterId
     * @param requesterIp
     * @param type
     * @param userid
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "viewOTP", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.ViewOTP")
    @ResponseWrapper(localName = "viewOTPResponse", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.ViewOTPResponse")
    @Action(input = "http://ws.waei.uba.com/Service/viewOTPRequest", output = "http://ws.waei.uba.com/Service/viewOTPResponse")
    public String viewOTP(
            @WebParam(name = "userid", targetNamespace = "")
                    String userid,
            @WebParam(name = "type", targetNamespace = "")
                    String type,
            @WebParam(name = "requesterId", targetNamespace = "")
                    String requesterId,
            @WebParam(name = "requesterIp", targetNamespace = "")
                    String requesterIp);

    /**
     * 
     * @param request
     * @return
     *     returns com.uba.waei.ws.GetContactInfoRespType
     */
    @WebMethod(operationName = "GetContactInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetContactInfo", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.GetContactInfo")
    @ResponseWrapper(localName = "GetContactInfoResponse", targetNamespace = "http://ws.waei.uba.com/", className = "com.uba.waei.ws.GetContactInfoResponse")
    @Action(input = "http://ws.waei.uba.com/Service/GetContactInfo", output = "http://ws.waei.uba.com/Service/GetContactInfoResponse")
    public GetContactInfoRespType getContactInfo(
            @WebParam(name = "request", targetNamespace = "")
                    GetContactInfoReqType request);

}
